# Generated by Django 4.2.7 on 2025-04-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0004_add_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='tool_result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
