# Generated by Django 4.2.7 on 2025-04-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0006_remove_chatmessage_tool_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='business',
        ),
        migrations.RenameField(
            model_name='businessprofile',
            old_name='resumes_screened',
            new_name='batches_screened',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='resumes_limit',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='batches_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='BulkResumeResult',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
