# Generated by Django 4.2.7 on 2025-04-24 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('screening', '0007_remove_chatmessage_business_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_plan', models.CharField(choices=[('free', 'Free Plan'), ('standard', 'Standard Plan'), ('premium', 'Premium Plan')], default='free', max_length=50)),
                ('subscription_start', models.DateTimeField(auto_now_add=True)),
                ('subscription_end', models.DateTimeField(blank=True, null=True)),
                ('resumes_screened', models.IntegerField(default=0)),
                ('resumes_limit', models.IntegerField(default=25)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='businessprofile',
            old_name='batches_screened',
            new_name='resumes_screened',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='batches_limit',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='resumes_limit',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free Plan'), ('standard', 'Standard Plan'), ('premium', 'Premium Plan'), ('enterprise', 'Enterprise Plan')], default='free', max_length=50),
        ),
        migrations.DeleteModel(
            name='BulkResumeScreen',
        ),
    ]
