# Generated by Django 4.2.7 on 2025-04-24 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0009_auto_20250424_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkResumeScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('required_skills', models.TextField()),
                ('preferred_experience', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('resumes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_screens', to='screening.businessprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkResumeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('ats_score', models.FloatField()),
                ('rank', models.IntegerField()),
                ('strengths', models.TextField()),
                ('weaknesses', models.TextField()),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bulk_screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='screening.bulkresumescreen')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_results', to='screening.resume')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
