# Generated by Django 4.2 on 2025-04-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screening", "0011_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="predicted_role",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="ranking",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="education",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="experience",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="resume",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="skills",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("reviewed", "Reviewed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
