# Generated by Django 4.2 on 2025-04-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screening", "0012_resume_predicted_role_resume_ranking_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="confidence_score",
            field=models.FloatField(default=75.0),
        ),
    ]
