# Generated by Django 4.2.7 on 2025-04-24 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='ats_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
